<?php

/**
 * @file
 * Contains one_time_grant.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function one_time_grant_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the one_time_grant module.
    case 'help.page.one_time_grant':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide a custom grant type for drupal/simple_auth.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function one_time_grant_theme() {
  return [
    'one_time_grant' => [
      'render element' => 'children',
    ],
  ];
}
